spring:
  config:
    import: env.yml

  application:
    name: ${APPLICATION_NAME}

---
spring:
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      globally_quoted_identifiers: true
      ddl-auto: update

---
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIA_URL}
    username: ${MARIA_USERNAME}
    password: ${MARIA_PASSWORD}