spring:
  config:
    import: env_production.yml

  application:
    name: ${APPLICATION_NAME}

---
spring:
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: ${AUTHORIZATION_URI}
            token-uri: ${TOKEN_URI}
            user-info-uri: ${USER_INFO_URI}
            user-name-attribute: id
        registration:
          kakao:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: ${REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname

---
spring:
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      globally_quoted_identifiers: true
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true # sql 보기 옵션
        #format_sql: true # 예쁘게 포맷팅
    #defer-datasource-initialization: true
  #sql:
    #init:
      #mode: always

---
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIA_URL}
    username: ${MARIA_USERNAME}
    password: ${MARIA_PASSWORD}


---
#로그
#security logging level
#logging:
#  level:
#    org:
#      springframework:
#        security: trace
#      zercok: debug

---
logging:
  level:
    com.example.marketapi: debug

---
jwt:
  header: Authorization
  secret: ${JWT_SECRET}
  token-validity-in-seconds: 86400
  key: ${JWT_SECRET}

---
spring:
  data:
    redis:
      port: 6379
      host: localhost